spring:
  application:
    name: edu
  datasource:
    url: jdbc:h2:tcp://localhost/~/edu
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      hibernate:
        SQL: debug
# SpringDoc 관련 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
application:
  name: Edu System Project
  version: 1.0.0
  description: Online learning system